<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/data_processing3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Removing duplicate values: drop_duplicates

In [58]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population_duplicates.csv')
df.head()

   rank  country     density   densityMi    pop2021   area
0     1    Macau  21946.4667  56841.3487    658.394     30
1     2   Monaco  19755.5000  51166.7450     39.511      2
2    28  Burundi    440.3044   1140.3884  12255.433  27834
3     1    Macau  21946.4667  56841.3487    658.394     30
4     2   Monaco  19755.5000  51166.7450     39.511      2

In [5]:
# checking duplicate values
df.duplicated()

0      False
1      False
2      False
3       True
4       True
       ...
242    False
243    False
244    False
245    False
246    False
Length: 247, dtype: bool

In [6]:
df[df.country == "Saint Martin"]

    rank       country   density  densityMi  pop2021  area
18    15  Saint Martin  740.2642  1917.2842   39.234    53
37    15  Saint Martin  740.2642  1917.2842   39.234    53

In [7]:
df.shape

(247, 6)

In [15]:
df.drop_duplicates()

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

In [18]:
df.drop_duplicates().shape

(232, 6)

In [19]:
# comparing based on a particular column
df.drop_duplicates(subset=['country'])

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

# ```.map()``` method

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/automobile_data.csv')
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [14]:
# printing unique values
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [28]:
# matching the unappropriate values with appropriate ones
nums = {'four': 4, 'six': 6, 'five': 5, 'three': 3, 'twelve':12, 'two':2, 'eight':8}
df['num-of-cylinders'].map(nums)
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,4,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,4,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,4,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,5,115,18,17450.0

In [29]:
# creating a column for the price in Uzbek currency
df['price_uzs'] = df['price'].map(lambda x: x * 12989)
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,price_uzs
0,0,alfa-romero,convertible,88.6,168.8,dohc,4,111,21,13495.0,175286555.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,4,111,21,16500.0,214318500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154,19,16500.0,214318500.0
3,3,audi,sedan,99.8,176.6,ohc,4,102,24,13950.0,181196550.0
4,4,audi,sedan,99.4,176.6,ohc,5,115,18,17450.0,226658050.0

# ```df.replace()``` method

In [34]:
df['num-of-cylinders'].unique()

array([ 4,  6,  5,  3, 12,  2,  8])

In [36]:
# df.replace() method
df['num-of-cylinders'].replace({2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six', 8: 'eight', 12: 'twelve'})

0     four
1     four
2      six
3     four
4     five
      ...
56    four
57    four
58    four
59    four
60    four
Name: num-of-cylinders, Length: 61, dtype: object

# ```df.rename()``` method

In [40]:
#
df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population_duplicates.csv')
df2.head()

   rank  country     density   densityMi    pop2021   area
0     1    Macau  21946.4667  56841.3487    658.394     30
1     2   Monaco  19755.5000  51166.7450     39.511      2
2    28  Burundi    440.3044   1140.3884  12255.433  27834
3     1    Macau  21946.4667  56841.3487    658.394     30
4     2   Monaco  19755.5000  51166.7450     39.511      2

In [42]:
df2.set_index('country', inplace = True)

In [43]:
df2.head()

         rank     density   densityMi    pop2021   area
country
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2
Burundi    28    440.3044   1140.3884  12255.433  27834
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2

In [46]:
df2.rename(index= str.upper, columns= str.upper, inplace = True)

In [55]:
df2.head()

         RANK     DENSITY   DENSITYMI    POP2021   AREA
country
MACAU       1  21946.4667  56841.3487    658.394     30
MONACO      2  19755.5000  51166.7450     39.511      2
BURUNDI    28    440.3044   1140.3884  12255.433  27834
MACAU       1  21946.4667  56841.3487    658.394     30
MONACO      2  19755.5000  51166.7450     39.511      2

In [56]:
df2.rename(columns = {'POP2021':'POPULATION'})

                  RANK     DENSITY   DENSITYMI  POPULATION     AREA
country
MACAU                1  21946.4667  56841.3487     658.394       30
MONACO               2  19755.5000  51166.7450      39.511        2
BURUNDI             28    440.3044   1140.3884   12255.433    27834
MACAU                1  21946.4667  56841.3487     658.394       30
MONACO               2  19755.5000  51166.7450      39.511        2
...                ...         ...         ...         ...      ...
NAMIBIA            228      3.1338      8.1166    2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577     611.875   266000
MONGOLIA           230      2.1286      5.5129    3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517       3.533    12173
GREENLAND          232      0.0263      0.0680      56.877  2166086

[247 rows x 5 columns]

In [52]:
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,price_uzs
0,0,alfa-romero,convertible,88.6,168.8,dohc,4,111,21,13495.0,175286555.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,4,111,21,16500.0,214318500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154,19,16500.0,214318500.0
3,3,audi,sedan,99.8,176.6,ohc,4,102,24,13950.0,181196550.0
4,4,audi,sedan,99.4,176.6,ohc,5,115,18,17450.0,226658050.0

# Grouping values: ```pd.cut()``` and ```pd.qcut()```

In [64]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population.csv', usecols = ['country', 'pop2021', 'area'], index_col = 'country')
df.head()

            pop2021  area
country
Macau       658.394    30
Monaco       39.511     2
Singapore  5896.686   710
Hong Kong  7552.810  1104
Gibraltar    33.698     6

In [67]:
df.pop2021

country
Macau                658.394
Monaco                39.511
Singapore           5896.686
Hong Kong           7552.810
Gibraltar             33.698
                      ...
Namibia             2587.344
Western Sahara       611.875
Mongolia            3329.289
Falkland Islands       3.533
Greenland             56.877
Name: pop2021, Length: 232, dtype: float64

In [86]:
boxes = [0, 10, 100, 1000, 5000, 10000, 30000, 50000, 100_000, 500_000, 1000_000, 1_500_000]

In [87]:
pop2021 = df.pop2021
pop2021

country
Macau                658.394
Monaco                39.511
Singapore           5896.686
Hong Kong           7552.810
Gibraltar             33.698
                      ...
Namibia             2587.344
Western Sahara       611.875
Mongolia            3329.289
Falkland Islands       3.533
Greenland             56.877
Name: pop2021, Length: 232, dtype: float64

In [88]:
groups = pd.cut(pop2021, bins=boxes)
groups

country
Macau                 (100, 1000]
Monaco                  (10, 100]
Singapore           (5000, 10000]
Hong Kong           (5000, 10000]
Gibraltar               (10, 100]
                        ...
Namibia              (1000, 5000]
Western Sahara        (100, 1000]
Mongolia             (1000, 5000]
Falkland Islands          (0, 10]
Greenland               (10, 100]
Name: pop2021, Length: 232, dtype: category
Categories (11, interval[int64, right]): [(0, 10] < (10, 100] < (100, 1000] < (1000, 5000] < ... <
                                          (50000, 100000] < (100000, 500000] < (500000, 1000000] <
                                          (1000000, 1500000]]

In [89]:
groups.value_counts()

pop2021
(10000, 30000]        44
(100, 1000]           38
(1000, 5000]          37
(5000, 10000]         31
(10, 100]             27
(30000, 50000]        19
(50000, 100000]       15
(100000, 500000]      12
(0, 10]                7
(1000000, 1500000]     2
(500000, 1000000]      0
Name: count, dtype: int64

In [90]:
pop2021.loc['India']

np.float64(1393409.038)

In [91]:
df['groups'] = groups

In [92]:
df

                   pop2021     area         groups
country
Macau              658.394       30    (100, 1000]
Monaco              39.511        2      (10, 100]
Singapore         5896.686      710  (5000, 10000]
Hong Kong         7552.810     1104  (5000, 10000]
Gibraltar           33.698        6      (10, 100]
...                    ...      ...            ...
Namibia           2587.344   825615   (1000, 5000]
Western Sahara     611.875   266000    (100, 1000]
Mongolia          3329.289  1564110   (1000, 5000]
Falkland Islands     3.533    12173        (0, 10]
Greenland           56.877  2166086      (10, 100]

[232 rows x 3 columns]

In [93]:
df.loc['Falkland Islands']

pop2021      3.533
area         12173
groups     (0, 10]
Name: Falkland Islands, dtype: object

In [94]:
df.loc['China']

pop2021           1444216.107
area                  9706961
groups     (1000000, 1500000]
Name: China, dtype: object

In [95]:
# Grouping and giving labels
# boxes = [0, 10, 100, 1000, 5000, 10000, 30000, 50000, 100_000, 500_000, 1000_000, 1_500_000]
names = ['nano', 'micro', 'mini', 'small', 'medium', 'average', 'big', 'large', 'huge', 'giant', 'colossal']
groups = pd.cut(pop2021, bins=boxes, labels=names)
groups

country
Macau                 mini
Monaco               micro
Singapore           medium
Hong Kong           medium
Gibraltar            micro
                     ...
Namibia              small
Western Sahara        mini
Mongolia             small
Falkland Islands      nano
Greenland            micro
Name: pop2021, Length: 232, dtype: category
Categories (11, object): ['nano' < 'micro' < 'mini' < 'small' ... 'large' < 'huge' < 'giant' <
                          'colossal']

In [96]:
df['pop_group'] = groups
df

                   pop2021     area         groups pop_group
country
Macau              658.394       30    (100, 1000]      mini
Monaco              39.511        2      (10, 100]     micro
Singapore         5896.686      710  (5000, 10000]    medium
Hong Kong         7552.810     1104  (5000, 10000]    medium
Gibraltar           33.698        6      (10, 100]     micro
...                    ...      ...            ...       ...
Namibia           2587.344   825615   (1000, 5000]     small
Western Sahara     611.875   266000    (100, 1000]      mini
Mongolia          3329.289  1564110   (1000, 5000]     small
Falkland Islands     3.533    12173        (0, 10]      nano
Greenland           56.877  2166086      (10, 100]     micro

[232 rows x 4 columns]

In [98]:
df.loc['India']

pop2021             1393409.038
area                    3287590
groups       (1000000, 1500000]
pop_group              colossal
Name: India, dtype: object

In [105]:
# grouping automatically
groups = pd.cut(pop2021, bins = 4)
groups.value_counts()

pop2021
(-1443.415, 361054.627]      230
(1083162.28, 1444216.107]      2
(361054.627, 722108.454]       0
(722108.454, 1083162.28]       0
Name: count, dtype: int64

In [111]:
# grouping equally
groups = pd.qcut(pop2021, q=4)
groups.value_counts()

pop2021
(0.799, 442.471]           58
(442.471, 5602.686]        58
(5602.686, 21497.15]       58
(21497.15, 1444216.107]    58
Name: count, dtype: int64