<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/data_processing2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Replacing nan values: ```.fillna()```

In [12]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data_nan.csv')
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [5]:
# replacing all nan values with a particular value
df.fillna(77)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,77.0,21.0,13495.0
1,1,alfa-romero,convertible,77.0,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,77.0,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,77.0,77.0,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
57,82,volkswagen,sedan,77.0,171.7,77,four,52.0,37.0,7995.0
58,86,volkswagen,sedan,97.3,77.0,ohc,four,100.0,77.0,9995.0
59,87,volvo,sedan,104.3,188.8,77,four,114.0,23.0,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,77.0,23.0,13415.0

In [6]:
# replacing only specific column values with particular values respectively
df.fillna({'wheel-base': 95, 'horsepower': 102})

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,102.0,21.0,13495.0
1,1,alfa-romero,convertible,95.0,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,102.0,NaN,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
57,82,volkswagen,sedan,95.0,171.7,NaN,four,52.0,37.0,7995.0
58,86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
59,87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,102.0,23.0,13415.0

In [10]:
# mean values
df.mean(numeric_only=True)

index                 40.885246
wheel-base            99.219565
length               173.852083
horsepower           108.266667
average-mileage       25.695652
price              15387.000000
dtype: float64

In [11]:
# replacing nan values with mean values
df.fillna(df.mean(numeric_only=True))

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.600000,168.800000,dohc,four,108.266667,21.000000,13495.0
1,1,alfa-romero,convertible,99.219565,168.800000,dohc,four,111.000000,21.000000,16500.0
2,2,alfa-romero,hatchback,94.500000,171.200000,ohcv,six,154.000000,25.695652,16500.0
3,3,audi,sedan,99.800000,176.600000,ohc,four,102.000000,24.000000,13950.0
4,4,audi,sedan,99.400000,176.600000,ohc,five,108.266667,25.695652,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.300000,171.700000,ohc,four,85.000000,27.000000,7975.0
57,82,volkswagen,sedan,99.219565,171.700000,NaN,four,52.000000,37.000000,7995.0
58,86,volkswagen,sedan,97.300000,173.852083,ohc,four,100.000000,25.695652,9995.0
59,87,volvo,sedan,104.300000,188.800000,NaN,four,114.000000,23.000000,12940.0
60,88,volvo,wagon,104.300000,188.800000,ohc,four,108.266667,23.000000,13415.0

In [14]:
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
57,82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
58,86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
59,87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [18]:
# forward filling
df.fillna(method='ffill')

<ipython-input-18-af5840deb760>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [19]:
# backward filling
df.fillna(method='bfill')

<ipython-input-19-d8b0f1738f6f>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
58,86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [22]:
df[df['company'] == 'audi']

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0