<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/multi_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hierarchical indexing

In [69]:
import pandas as pd
import numpy as np

In [ ]:
foods = ['apple', 'banana', 'plumb', 'graips', 'mellon', 'berry', 'watermellon', 'apricot', 'pumpkin']

In [ ]:
data = pd.Series(foods, index=['a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'])
data

a          apple
a         banana
b          plumb
b         graips
b         mellon
c          berry
c    watermellon
d        apricot
d        pumpkin
dtype: object

In [ ]:
data.index

Index(['a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'], dtype='object')

In [ ]:
data1 = pd.Series(foods,
                  index= [['a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'], [1, 2, 3, 2, 1, 2, 1, 2, 3]]
                  )
data1

a  1          apple
   2         banana
b  3          plumb
   2         graips
   1         mellon
c  2          berry
   1    watermellon
d  2        apricot
   3        pumpkin
dtype: object

In [ ]:
data1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 3),
            ('b', 2),
            ('b', 1),
            ('c', 2),
            ('c', 1),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
data1['a']
data1.loc['a', 2]

'banana'

# .stack() and .unstack() methods

In [ ]:
data2 = data1.unstack()
data2

             1        2        3
a        apple   banana      NaN
b       mellon   graips    plumb
c  watermellon    berry      NaN
d          NaN  apricot  pumpkin

In [ ]:
data2.stack()

a  1          apple
   2         banana
b  1         mellon
   2         graips
   3          plumb
c  1    watermellon
   2          berry
d  2        apricot
   3        pumpkin
dtype: object

# practising with real data

In [70]:
df = pd.read_csv('https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/world_cities_air_water_quality.csv')
df

,City,"""Region""","""Country""","""AirQuality""","""WaterPollution"""
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [71]:
df.columns = df.columns.map(lambda x: x.replace('"', '')).map(lambda x: x.strip())
df.columns

Index(['City', 'Region', 'Country', 'AirQuality', 'WaterPollution'], dtype='object')

In [72]:
columns = ['City', 'Region', 'Country', 'AirQuality', 'WaterPollution']
df.columns = columns
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [73]:
df['Region'] = df['Region'].map(lambda x: x.replace('"', ''))
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,"""United States of America""",46.816038,49.504950
1,"Washington, D.C.",District of Columbia,"""United States of America""",66.129032,49.107143
2,San Francisco,California,"""United States of America""",60.514019,43.000000
3,Berlin,,"""Germany""",62.364130,28.612717
4,Los Angeles,California,"""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,"""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,Andalusia,"""Spain""",85.714286,8.333333
3960,Vic,Catalonia,"""Spain""",100.000000,0.000000
3961,Segovia,Castile and Leon,"""Spain""",100.000000,0.000000
3962,Zamora city,Castile and Leon,"""Spain""",100.000000,50.000000

In [74]:
df['Country'] = df['Country'].map(lambda x: x.replace('"', ""))
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3963 entries, 0 to 3962
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   City            3963 non-null   object
 1   Region          3963 non-null   object
 2   Country         3963 non-null   object
 3   AirQuality      3963 non-null   float64
 4   WaterPollution  3963 non-null   float64
dtypes: float64(2), object(3)
memory usage: 154.9+ KB

In [76]:
df.describe()

        AirQuality  WaterPollution
count  3963.000000     3963.000000
mean     62.253452       44.635372
std      30.944753       25.663910
min       0.000000        0.000000
25%      37.686567       25.000000
50%      69.444444       50.000000
75%      87.500000       57.719393
max     100.000000      100.000000

In [ ]:
df.head(20)

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
5,Bern,Canton of Bern,Switzerland,94.318182,12.500000
6,Geneva,Canton of Geneva,Switzerland,71.538462,17.372881
7,Zurich,Canton of Zurich,Switzerland,83.809524,10.714286
8,Basel,,Switzerland,81.666667,26.923077
9,London,England,United Kingdom,37.042254,40.716374
10,Cairo,Cairo Governorate,Egypt,15.830721,74.350649
11,Alexandria,Alexandria Governorate,Egypt,41.037736,71.296296
12,Alexandria,Virginia,United States of America,89.062500,46.153846
13,Paris,Ile-de-France,France,34.024390,43.121693
14,Boston,Massachusetts,United States of America,78.235294,32.911392
15,Toronto,Ontario,Canada,65.534682,37.799401
16,Sao Paulo,Sao Paulo,Brazil,24.056604,73.717949
17,Vilnius,,Lithuania,77.247191,20.588235
18,Monaco,,Monaco,28.787879,61.363636
19,Brussels,,Belgium,35.810811,44.761905

In [ ]:
df[df['Country'] == 'Germany']

Empty DataFrame
Columns: [City, Region, Country, AirQuality, WaterPollution]
Index: []

In [ ]:
df['Country'][1]

' United States of America'

In [77]:
# removing whitespaces
df['Country'] = df['Country'].map(lambda x: x.strip())
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [ ]:
df[df['Country'] == 'Uzbekistan']

        City Region     Country  AirQuality  WaterPollution
21  Tashkent         Uzbekistan   56.451613       49.166667

In [ ]:
df[(df['Country'] == "Germany") & (df['City'] == 'Heilbronn')]

         City              Region  Country  AirQuality  WaterPollution
52  Heilbronn   Baden-Wurttemberg  Germany        80.0             0.0

In [ ]:
df[(df["Country"] == 'United States of America') & (df["City"] == 'Ithaca')]

        City     Region                   Country  AirQuality  WaterPollution
3727  Ithaca   Michigan  United States of America       93.75          40.625

In [ ]:
df[(df["Country"] == 'Canada') & (df["City"] == 'Toronto')]

       City    Region Country  AirQuality  WaterPollution
15  Toronto   Ontario  Canada   65.534682       37.799401

# making the dataset hierarchically indexed

In [ ]:
# .set_index() method
df.set_index(['Country', 'City'])

                                                          Region  AirQuality  \
Country                  City
United States of America New York City                  New York   46.816038
                         Washington, D.C.   District of Columbia   66.129032
                         San Francisco                California   60.514019
Germany                  Berlin                                    62.364130
United States of America Los Angeles                  California   36.621622
...                                                          ...         ...
Saudi Arabia             Yanbu                   Medina Province    0.000000
Spain                    Cordoba                       Andalusia   85.714286
                         Vic                           Catalonia  100.000000
                         Segovia                Castile and Leon  100.000000
                         Zamora city            Castile and Leon  100.000000

                                           WaterPollution
Country                  City
United States of America New York City          49.504950
                         Washington, D.C.       49.107143
                         San Francisco          43.000000
Germany                  Berlin                 28.612717
United States of America Los Angeles            61.299435
...                                                   ...
Saudi Arabia             Yanbu                  50.000000
Spain                    Cordoba                 8.333333
                         Vic                     0.000000
                         Segovia                 0.000000
                         Zamora city            50.000000

[3963 rows x 3 columns]

In [78]:
# .pivot_table() method
df1 = df.pivot_table(index= ['Country', 'City'], values = ['AirQuality', 'WaterPollution'] )
df1.head(10)

                            AirQuality  WaterPollution
Country     City
Afghanistan Andkhoy          50.000000       50.000000
            Farah           100.000000        0.000000
            Herat            43.750000       31.250000
            Kabul            18.421053       81.060606
            Kandahar          0.000000       75.000000
            Mazar-i-Sharif   11.111111       83.333333
Albania     Ballsh            0.000000       62.500000
            Burrel          100.000000       62.500000
            Durres           37.500000       62.500000
            Elbasan           0.000000       25.000000

In [ ]:
df1.loc[['Canada', 'Germany', 'United Kingdom']]

                           AirQuality  WaterPollution
Country        City
Canada         Abbotsford   64.285714       36.458333
               Airdrie      62.500000       25.000000
               Ajax         87.500000       38.636364
               Arnprior    100.000000       25.000000
               Aurora       50.000000       37.500000
...                               ...             ...
United Kingdom Worcester    83.333333       16.666667
               Worthing     75.000000       31.250000
               Wrexham      83.333333        0.000000
               Yeovil       62.500000       37.500000
               York         81.818182       18.750000

[451 rows x 2 columns]

In [ ]:
df1.loc['United Kingdom', 'Cambridge']

AirQuality        69.827586
WaterPollution    30.555556
Name: (United Kingdom, Cambridge), dtype: float64

In [ ]:
df1.loc['United Kingdom', 'Oxfordx']

AirQuality        78.7500
WaterPollution    26.5625
Name: (United Kingdom, Oxford), dtype: float64

In [ ]:
df1.loc['Uzbekistan']

          AirQuality  WaterPollution
City
Tashkent   56.451613       49.166667

# hierarchic columns

In [79]:
df2 = df1.copy()
df2

                      AirQuality  WaterPollution
Country     City
Afghanistan Andkhoy    50.000000       50.000000
            Farah     100.000000        0.000000
            Herat      43.750000       31.250000
            Kabul      18.421053       81.060606
            Kandahar    0.000000       75.000000
...                          ...             ...
Zambia      Mansa      75.000000       25.000000
Zimbabwe    Bindura    50.000000       75.000000
            Bulawayo   67.857143       71.428571
            Harare     38.461538       87.500000
            Masvingo   25.000000       62.500000

[3895 rows x 2 columns]

In [80]:
df2['AirPollution'] = 100 - df2['AirQuality']
df2

                      AirQuality  WaterPollution  AirPollution
Country     City
Afghanistan Andkhoy    50.000000       50.000000     50.000000
            Farah     100.000000        0.000000      0.000000
            Herat      43.750000       31.250000     56.250000
            Kabul      18.421053       81.060606     81.578947
            Kandahar    0.000000       75.000000    100.000000
...                          ...             ...           ...
Zambia      Mansa      75.000000       25.000000     25.000000
Zimbabwe    Bindura    50.000000       75.000000     50.000000
            Bulawayo   67.857143       71.428571     32.142857
            Harare     38.461538       87.500000     61.538462
            Masvingo   25.000000       62.500000     75.000000

[3895 rows x 3 columns]

In [81]:
df2['WaterQuality'] = 100 - df2['WaterPollution']
df2

                      AirQuality  WaterPollution  AirPollution  WaterQuality
Country     City
Afghanistan Andkhoy    50.000000       50.000000     50.000000     50.000000
            Farah     100.000000        0.000000      0.000000    100.000000
            Herat      43.750000       31.250000     56.250000     68.750000
            Kabul      18.421053       81.060606     81.578947     18.939394
            Kandahar    0.000000       75.000000    100.000000     25.000000
...                          ...             ...           ...           ...
Zambia      Mansa      75.000000       25.000000     25.000000     75.000000
Zimbabwe    Bindura    50.000000       75.000000     50.000000     25.000000
            Bulawayo   67.857143       71.428571     32.142857     28.571429
            Harare     38.461538       87.500000     61.538462     12.500000
            Masvingo   25.000000       62.500000     75.000000     37.500000

[3895 rows x 4 columns]

In [85]:
df3 = pd.DataFrame(df2.values, index = df2.index, columns = [['Air', 'Air', 'Water', 'Water'], ['AirQuality', 'AirPollution', 'WaterQuality', 'WaterPollution']])
df3

                             Air                     Water
                      AirQuality AirPollution WaterQuality WaterPollution
Country     City
Afghanistan Andkhoy    50.000000    50.000000    50.000000      50.000000
            Farah     100.000000     0.000000     0.000000     100.000000
            Herat      43.750000    31.250000    56.250000      68.750000
            Kabul      18.421053    81.060606    81.578947      18.939394
            Kandahar    0.000000    75.000000   100.000000      25.000000
...                          ...          ...          ...            ...
Zambia      Mansa      75.000000    25.000000    25.000000      75.000000
Zimbabwe    Bindura    50.000000    75.000000    50.000000      25.000000
            Bulawayo   67.857143    71.428571    32.142857      28.571429
            Harare     38.461538    87.500000    61.538462      12.500000
            Masvingo   25.000000    62.500000    75.000000      37.500000

[3895 rows x 4 columns]

In [95]:
df3[df3['Air', 'AirQuality'] < 50].loc["Canada", "Air"]

             AirQuality  AirPollution
City
Bowmanville     0.00000    100.000000
Hamilton       42.79661     54.017857
Morden         25.00000     50.000000
Salmon Arm     25.00000     75.000000
Welland        45.00000     45.000000

In [97]:
df3.head()

                             Air                     Water
                      AirQuality AirPollution WaterQuality WaterPollution
Country     City
Afghanistan Andkhoy    50.000000    50.000000    50.000000      50.000000
            Farah     100.000000     0.000000     0.000000     100.000000
            Herat      43.750000    31.250000    56.250000      68.750000
            Kabul      18.421053    81.060606    81.578947      18.939394
            Kandahar    0.000000    75.000000   100.000000      25.000000

In [98]:
df3.columns.names = ['Object', "info"]
df3

Object                       Air                     Water
info                  AirQuality AirPollution WaterQuality WaterPollution
Country     City
Afghanistan Andkhoy    50.000000    50.000000    50.000000      50.000000
            Farah     100.000000     0.000000     0.000000     100.000000
            Herat      43.750000    31.250000    56.250000      68.750000
            Kabul      18.421053    81.060606    81.578947      18.939394
            Kandahar    0.000000    75.000000   100.000000      25.000000
...                          ...          ...          ...            ...
Zambia      Mansa      75.000000    25.000000    25.000000      75.000000
Zimbabwe    Bindura    50.000000    75.000000    50.000000      25.000000
            Bulawayo   67.857143    71.428571    32.142857      28.571429
            Harare     38.461538    87.500000    61.538462      12.500000
            Masvingo   25.000000    62.500000    75.000000      37.500000

[3895 rows x 4 columns]

In [99]:
df3.index.names

FrozenList(['Country', 'City'])

# Swapping indices

In [101]:
df3.swaplevel('Country', 'City')

Object                       Air                     Water
info                  AirQuality AirPollution WaterQuality WaterPollution
City     Country
Andkhoy  Afghanistan   50.000000    50.000000    50.000000      50.000000
Farah    Afghanistan  100.000000     0.000000     0.000000     100.000000
Herat    Afghanistan   43.750000    31.250000    56.250000      68.750000
Kabul    Afghanistan   18.421053    81.060606    81.578947      18.939394
Kandahar Afghanistan    0.000000    75.000000   100.000000      25.000000
...                          ...          ...          ...            ...
Mansa    Zambia        75.000000    25.000000    25.000000      75.000000
Bindura  Zimbabwe      50.000000    75.000000    50.000000      25.000000
Bulawayo Zimbabwe      67.857143    71.428571    32.142857      28.571429
Harare   Zimbabwe      38.461538    87.500000    61.538462      12.500000
Masvingo Zimbabwe      25.000000    62.500000    75.000000      37.500000

[3895 rows x 4 columns]

In [106]:
df3.sort_index(level=0, ascending = False)

Object                       Air                     Water
info                  AirQuality AirPollution WaterQuality WaterPollution
Country     City
Zimbabwe    Masvingo   25.000000    62.500000    75.000000      37.500000
            Harare     38.461538    87.500000    61.538462      12.500000
            Bulawayo   67.857143    71.428571    32.142857      28.571429
            Bindura    50.000000    75.000000    50.000000      25.000000
Zambia      Mansa      75.000000    25.000000    25.000000      75.000000
...                          ...          ...          ...            ...
Afghanistan Kandahar    0.000000    75.000000   100.000000      25.000000
            Kabul      18.421053    81.060606    81.578947      18.939394
            Herat      43.750000    31.250000    56.250000      68.750000
            Farah     100.000000     0.000000     0.000000     100.000000
            Andkhoy    50.000000    50.000000    50.000000      50.000000

[3895 rows x 4 columns]